// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKJk7NOs2wQZq2tH3JoMEkYNGeotfAMHM',
    appId: '1:500725075487:web:8578ece49da71447d3cf2a',
    messagingSenderId: '500725075487',
    projectId: 'crud-test-85aa9',
    authDomain: 'crud-test-85aa9.firebaseapp.com',
    storageBucket: 'crud-test-85aa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm5f-edW1VTwrbv4gqhlz2inD3K0Ob1LM',
    appId: '1:500725075487:android:c017f4fcdbcd9323d3cf2a',
    messagingSenderId: '500725075487',
    projectId: 'crud-test-85aa9',
    storageBucket: 'crud-test-85aa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhBp2PAWYsqv-mFHNiGi0DYDn98CoikbU',
    appId: '1:500725075487:ios:2878c1020f8337b4d3cf2a',
    messagingSenderId: '500725075487',
    projectId: 'crud-test-85aa9',
    storageBucket: 'crud-test-85aa9.appspot.com',
    iosBundleId: 'com.agrgal.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhBp2PAWYsqv-mFHNiGi0DYDn98CoikbU',
    appId: '1:500725075487:ios:2878c1020f8337b4d3cf2a',
    messagingSenderId: '500725075487',
    projectId: 'crud-test-85aa9',
    storageBucket: 'crud-test-85aa9.appspot.com',
    iosBundleId: 'com.agrgal.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKJk7NOs2wQZq2tH3JoMEkYNGeotfAMHM',
    appId: '1:500725075487:web:80fd746a16607895d3cf2a',
    messagingSenderId: '500725075487',
    projectId: 'crud-test-85aa9',
    authDomain: 'crud-test-85aa9.firebaseapp.com',
    storageBucket: 'crud-test-85aa9.appspot.com',
  );
}
